Created By: 190133107026

## Import Numpy 

In [ ]:
import numpy as np

# To access file from local machine

## From a local drive

In [ ]:
from google.colab import files
uploaded = files.upload()
# select covid.csv from the local drive.

Saving covid.csv to covid.csv


In [ ]:
arr = np.genfromtxt('covid.csv', delimiter=",")

### Print Array

In [ ]:
arr

array([[nan, nan, nan, ..., nan, nan, nan],
       [nan,  2.,  1., ...,  2.,  1., 97.],
       [nan,  2.,  1., ..., 99.,  1., 97.],
       ...,
       [nan,  1.,  2., ..., 99.,  3.,  2.],
       [nan,  1.,  1., ...,  2.,  3., 97.],
       [nan,  2.,  1., ...,  2.,  3., 97.]])

### Finding the data type of elements in the NumPy array

In [ ]:
arr.dtype

dtype('float64')

### Get the Shape of an Array

In [ ]:
arr.shape

(566603, 23)

### Numpy size() function | Python

In [ ]:
arr.size

13031869

### Get the memory space occupied by an n-dimensional array

In [ ]:
arr.nbytes

104254952

### Get an n-dimensional array of ones.

In [ ]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### Get an n-dimensional array of zeros.

In [ ]:
zeros = np.zeros((2,5))

In [ ]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### Getting an array of evenly spaced values with np.arrange and np.linspace

In [ ]:
rng =  np.arange(10)

In [ ]:
rng

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
lsplace = np.linspace(1,4,3)

In [ ]:
lsplace

array([1. , 2.5, 4. ])

In [ ]:
arr.shape

(13031869,)

In [ ]:

np.random.randint(2, size=10)


array([0, 0, 1, 1, 0, 0, 0, 1, 1, 1])

In [ ]:
a = np.array([[1,2,3],[4,8,16]])
a

array([[ 1,  2,  3],
       [ 4,  8, 16]])

In [ ]:
b = np.array([5,6,11]).reshape(-1,1)
b

array([[ 5],
       [ 6],
       [11]])

In [ ]:
np.dot(a,b)

array([[ 50],
       [244]])

### np.full and np.empty

In [ ]:
np.full(3,5)

array([5, 5, 5])

In [ ]:
emp = np.empty((2,3))

In [ ]:
emp

array([[1.26925385e-316, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [ ]:
emp_like = np.empty_like(lsplace)

In [ ]:
emp_like 

array([1. , 2.5, 4. ])

### identity() Function

In [ ]:
ide = np.identity(3)

In [ ]:
ide

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
ide.shape

(3, 3)

### shape, arange, reshape, ravel

In [ ]:
arr2 = np.arange(99)

In [ ]:
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [ ]:
arr2.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [ ]:
arr = arr.ravel()

In [ ]:
arr.shape

(13031869,)

### Standard deviation along the specified axis.

In [ ]:
arr.std

<function ndarray.std>

In [ ]:
x = [[1,2,3],[4,5,6],[7,1,0]]

In [ ]:
ar = np.array(x)

In [ ]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [ ]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [ ]:
ar.sum(axis=0)

array([12,  8,  9])

### Get transpose of an n-d array

In [ ]:
arr.T

array([nan, nan, nan, ...,  2.,  3., 97.])

In [ ]:
arr.flat

In [ ]:
for item in ar.flat:
  print(item)

1
2
3
4
5
6
7
1
0


### Knowing the dimensions of the NumPy array

In [ ]:
arr.ndim

1

In [ ]:
arr.nbytes

104254952

In [ ]:
ar.argmax()

6

In [ ]:
ar.argmin()

8

Sort NumPy array

In [ ]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

In [ ]:
ar.argmax(axis=0)

array([2, 1, 1])

In [ ]:
ar.argmax(axis=1)

array([2, 2, 0])

In [ ]:
ar.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [ ]:
np.where(arr>25)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in greater
  """Entry point for launching an IPython kernel.


(array([      29,       31,       32, ..., 13031854, 13031855, 13031868]),)

In [ ]:
type(np.where(arr>25))

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in greater
  """Entry point for launching an IPython kernel.


tuple

Get indices of non-zero elements

In [ ]:
np.count_nonzero(arr)

13026387

In [ ]:
 np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1]))

In [ ]:
import sys

In [ ]:
sys.getsizeof(arr) *len(arr)

1251059424

In [ ]:
arr.itemsize * arr.size

104254952

In [ ]:
np.diag(np.diag(arr))

MemoryError: ignored

In [ ]:
a = np.eye(2) 

In [ ]:
a

array([[1., 0.],
       [0., 1.]])

In [ ]:
b = np.array([[1,2],[3,4]])

In [ ]:
b

array([[1, 2],
       [3, 4]])

In [ ]:
np.matmul(a,b) 

array([[1., 2.],
       [3., 4.]])

### Get cross-product of two numpy vectors

In [ ]:
x = [1,2,3]
y = [4,5,6]
z = np.cross(x, y)

In [ ]:
z


array([-3,  6, -3])

### Getting gradient of an array

In [ ]:
np.gradient(arr)

array([ nan,  nan,  nan, ...,  0.5, 47.5, 94. ])

### Slice NumPy array

In [ ]:
ar[[0,2],0:2]

array([[1, 2],
       [7, 1]])

### Dot product of two arrays

In [ ]:
a = np.array([[1,2,3],[4,8,16]])

In [ ]:
a

array([[ 1,  2,  3],
       [ 4,  8, 16]])

In [ ]:
b = np.array([5,6,11]).reshape(-1,1)

In [ ]:
b

array([[ 5],
       [ 6],
       [11]])

In [ ]:
np.dot(a,b) 

array([[ 50],
       [244]])

### Multiply two NumPy matrices

In [ ]:
a = np.eye(2)

In [ ]:
a

array([[1., 0.],
       [0., 1.]])

In [ ]:
b = np.array([[1,2],[3,4]])

In [ ]:
b

array([[1, 2],
       [3, 4]])

In [ ]:
np.multiply(a,b)

array([[1., 0.],
       [0., 4.]])